#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python manage.py loaddata data/file/data.json
python manage.py collectstatic --noinput
python manage.py runserver 0.0.0.0:8000

